In [1]:
import numpy as np
myArray = np.full((2,4), range(11,19))
print(myArray)

ValueError: could not broadcast input array from shape (8,) into shape (2,4)

In [2]:
myArray = np.array([range(i, i+4) for i in [11,15]])
print(myArray)

[[11 12 13 14]
 [15 16 17 18]]


In [3]:
zerosArray = np.zeros((4,3))
print(zerosArray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
onesArray = np.ones((3,4))
print(onesArray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
arrayZero = np.arange(4,14)
print(arrayZero)

[ 4  5  6  7  8  9 10 11 12 13]


In [9]:
arrayOne = np.arange(0,5,1.5, dtype = float)
print(arrayOne)

[0.  1.5 3.  4.5]


In [2]:
arrayTwo = np.full((2,2), 4)
print(arrayTwo)

[[4 4]
 [4 4]]


In [3]:
import numpy as np
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
diagonalMatrix = np.diag(10,12)
print(diagonalMatrix)

ValueError: Input must be 1- or 2-d.

In [5]:
diagonalMatrix = np.diag([10,12])
print(diagonalMatrix)

[[10  0]
 [ 0 12]]


In [12]:
randomFloats3x3 = np.random.uniform(10, size=(3,3))
print(randomFloats3x3)

[[5.84378224 6.43514972 9.79233373]
 [4.39771677 2.36047456 6.67851531]
 [7.9242505  4.19251159 1.37353141]]


In [15]:
randomInts = np.random.randint(10, 21, size=(3,3))
print(randomInts)

[[17 12 15]
 [18 17 17]
 [12 11 10]]


In [16]:
myArray = np.array([[11,12,13],[14,15,16],[17,18,19]])
subarray = myArray[:1, :2]
print(subarray)

[[11 12]]


In [19]:
myArray[:2] = 0
print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [20]:
toTwenty = np.arange(0,21, 1)
print(toTwenty)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
toTwenty = toTwenty[::-1]
print(toTwenty)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [22]:
myArray = np.array([[11,12,13], [14,15,16]])
myArray.shape

(2, 3)

In [26]:
myArray = myArray.reshape((3,2))
print(myArray)

[[11 12]
 [13 14]
 [15 16]]


In [69]:
myArray = np.arange(10)
print(myArray)
allSquares = myArray**2
allSquareRoots = myArray**(1/2)
allSquareProducts = (myArray**2) * (myArray**(1/2)) 
print(allSquares)
print(allSquareRoots)
print(allSquareProducts)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [30]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(myArray)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [37]:
combined = np.concatenate([myArray, [[20,21,22]]])
print(combined)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [42]:
column = np.array([
    [30],
    [40],
    [50]
])
columnCombined = np.hstack((column, myArray))
print(columnCombined)

[[30 11 12 13]
 [40 14 15 16]
 [50 17 18 19]]


In [43]:
myArray = np.zeros((2,2))
column = np.ones((2,1))
final = np.hstack((myArray, column))
print(final)

[[0. 0. 1.]
 [0. 0. 1.]]


In [45]:
rows = np.full((2,3), 2.)
print(rows)

[[2. 2. 2.]
 [2. 2. 2.]]


In [49]:
final = np.concatenate((final, rows))
print(final)

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [50]:
final = final[:4, :2]
print(final)

[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]]


In [51]:
final = final[:3]
print(final)

[[0. 0.]
 [0. 0.]
 [2. 2.]]


In [52]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
myArray = myArray[:3, :3:2]
print(myArray)

[[1 3]
 [4 6]
 [9 7]]


In [58]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1%2==1] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [62]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
exercise_2=exercise_2.reshape((3,3))
print(exercise_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
exercise_3 = np.arange(4).reshape(2,-1)
exercise_3 += 202
print(exercise_3)

[[202 203]
 [204 205]]


In [64]:
exercise_4 = np.random.randint(30, 41, 10)
print(exercise_4)

[40 36 30 34 39 38 38 31 31 35]


In [70]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
z = np.where(x==y)
print(z)

(array([0]),)


In [71]:
k = np.where(x>y)
print(k)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)


In [76]:
exercise_6 = np.arange(100).reshape(5,-1)
exercise_6 = exercise_6[:5, :4]
print(exercise_6)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
